import 'server-only'

import { unstable_cache } from 'next/cache'
import { createAdminClient } from '@/lib/supabase/admin'
import { recordCanonicalEvent, type CanonicalCommerceEvent } from './events'
import { ANALYTICS_EVENT_MAP } from './registry'
import { buildServerGtmEnvelope } from './server-gtm'

export type AnalyticsConfig = { enabled: boolean; marketingEnabled: boolean; consentMode: 'basic' | 'advanced'; debugMode: boolean; ga4MeasurementId: string; gtmContainerId: string; metaPixelId: string; metaCapiEnabled: boolean; tiktokPixelId: string; tiktokEventsApiEnabled: boolean; serverGtmEnabled: boolean; serverGtmEndpoint: string; environment: 'development' | 'preview' | 'production'; eventControls: Record<string, boolean> }
export const DEFAULT_ANALYTICS_CONFIG: AnalyticsConfig = { enabled: false, marketingEnabled: false, consentMode: 'advanced', debugMode: false, ga4MeasurementId: '', gtmContainerId: '', metaPixelId: '', metaCapiEnabled: false, tiktokPixelId: '', tiktokEventsApiEnabled: false, serverGtmEnabled: false, serverGtmEndpoint: '', environment: process.env.VERCEL_ENV === 'production' ? 'production' : process.env.VERCEL_ENV === 'preview' ? 'preview' : 'development', eventControls: {} }

const readConfig = unstable_cache(async (): Promise<AnalyticsConfig> => { try { const db = createAdminClient(); const { data } = await db.from('settings').select('value').eq('key', 'analytics_config').maybeSingle(); const stored = (data?.value as Partial<AnalyticsConfig> | null) || {}; return { ...DEFAULT_ANALYTICS_CONFIG, ...stored, eventControls: { ...DEFAULT_ANALYTICS_CONFIG.eventControls, ...(stored.eventControls || {}) }, environment: DEFAULT_ANALYTICS_CONFIG.environment } } catch { return DEFAULT_ANALYTICS_CONFIG } }, ['analytics-config-v2'], { revalidate: 60, tags: ['analytics-config'] });
export async function getAnalyticsConfig() { return readConfig() }

async function postJson(url: string, body: unknown, headers: Record<string, string> = {}) { for (let attempt = 0; attempt < 2; attempt += 1) { const started = Date.now(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 3500); try { const response = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json', ...headers }, body: JSON.stringify(body), signal: controller.signal, cache: 'no-store' }); const latency = Date.now() - started; if (response.ok) return { ok: true, latency }; if (response.status < 500) return { ok: false, latency, category: 'HTTP_ERROR' } } catch (error) { const latency = Date.now() - started; if (attempt === 1) return { ok: false, latency, category: error instanceof Error && error.name === 'AbortError' ? 'TIMEOUT' : 'NETWORK_ERROR' } } finally { clearTimeout(timer) } } return { ok: false, category: 'RETRY_EXHAUSTED' } }

function ga4Payload(event: CanonicalCommerceEvent) { return { client_id: event.anonymousId || event.sessionId || event.eventId, events: [{ name: event.eventName.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase(), params: { ...event.commerce, event_id: event.eventId, session_id: event.sessionId || undefined, engagement_time_msec: 1 } }], consent: { analytics_storage: event.consent.analytics ? 'GRANTED' : 'DENIED', ad_user_data: event.consent.marketing ? 'GRANTED' : 'DENIED', ad_personalization: event.consent.marketing ? 'GRANTED' : 'DENIED' } } }
function metaPayload(event: CanonicalCommerceEvent) { return { data: [{ event_name: event.eventName, event_time: Math.floor(new Date(event.occurredAt).getTime() / 1000), event_id: event.eventId, action_source: 'website', user_data: {}, custom_data: event.commerce || {} }] } }
function tiktokEventName(name: CanonicalCommerceEvent['eventName']) { const map: Record<string,string> = { page_view: 'PageView', view_item: 'ViewContent', view_item_list: 'ViewContent', search: 'Search', add_to_cart: 'AddToCart', begin_checkout: 'InitiateCheckout', add_shipping_info: 'AddPaymentInfo', add_payment_info: 'AddPaymentInfo', purchase: 'CompletePayment', generate_lead: 'SubmitForm', contact: 'Contact', sign_up: 'CompleteRegistration', whatsapp_click: 'Contact' }; return map[name] || name }
function tiktokPayload(event: CanonicalCommerceEvent) { const commerce = event.commerce || {}; const items = Array.isArray(commerce.items) ? commerce.items : []; return { event_source: 'web', event_source_id: '', data: [{ event: tiktokEventName(event.eventName), event_time: Math.floor(new Date(event.occurredAt).getTime() / 1000), event_id: event.eventId, properties: { currency: commerce.currency || 'BDT', value: typeof commerce.value === 'number' ? commerce.value : undefined, contents: items.map((item) => { const x = item as Record<string, unknown>; return { content_id: x.item_id, content_name: x.item_name, quantity: x.quantity, price: x.price }; }), content_type: 'product', query: commerce.search_term }, page: { url: event.pageUrl || undefined, referrer: event.referrer || undefined } }] } }

export async function dispatchAnalyticsEvent(event: CanonicalCommerceEvent) { const config = await readConfig(); const definition = ANALYTICS_EVENT_MAP[event.eventName]
  if (!config.enabled || (!definition?.required && config.eventControls[event.eventName] === false) || !event.consent.analytics || (event.testMode !== true && config.environment === 'development' && !config.debugMode)) return { ok: true, skipped: true, destinations: [] as string[] }; const deliveries: Array<{ destination: string; ok: boolean; category?: string; latency?: number }> = []; const destinations: Promise<void>[] = []
  const ga4Secret = process.env.GA4_API_SECRET
  if (config.ga4MeasurementId && ga4Secret) destinations.push(postJson(`https://www.google-analytics.com/mp/collect?measurement_id=${encodeURIComponent(config.ga4MeasurementId)}&api_secret=${encodeURIComponent(ga4Secret)}`, ga4Payload(event)).then((result) => { deliveries.push({ destination: 'GA4', ...result }) }))
  if (config.marketingEnabled && event.consent.marketing && config.metaCapiEnabled && process.env.META_CAPI_ACCESS_TOKEN && config.metaPixelId) destinations.push(postJson(`https://graph.facebook.com/v20.0/${encodeURIComponent(config.metaPixelId)}/events?access_token=${encodeURIComponent(process.env.META_CAPI_ACCESS_TOKEN)}`, metaPayload(event)).then((result) => { deliveries.push({ destination: 'META_CAPI', ...result }) }))
  if (config.tiktokEventsApiEnabled && config.tiktokPixelId && process.env.TIKTOK_EVENTS_API_ACCESS_TOKEN && event.consent.marketing && event.testMode !== true) { const payload = tiktokPayload(event); payload.event_source_id = config.tiktokPixelId; destinations.push(postJson('https://business-api.tiktok.com/open_api/v1.3/event/track/', payload, { 'Access-Token': process.env.TIKTOK_EVENTS_API_ACCESS_TOKEN }).then((result) => { deliveries.push({ destination: 'TIKTOK_EVENTS_API', ...result }) })) }
  if (config.serverGtmEnabled && config.serverGtmEndpoint && event.testMode !== true) destinations.push(postJson(config.serverGtmEndpoint, buildServerGtmEnvelope(event)).then((result) => { deliveries.push({ destination: 'SERVER_GTM', ...result }) }))
  await Promise.allSettled(destinations); return { ok: deliveries.every((item) => item.ok), skipped: false, deliveries }
}

export async function trackServerCommerceEvent(input: CanonicalCommerceEvent & { orderId?: string | null; cartId?: string | null }) { try { const persisted = await recordCanonicalEvent(input); if (!persisted.ok || persisted.duplicate) return { ...persisted, deliveries: [] }; return { ...persisted, ...(await dispatchAnalyticsEvent(input)) } } catch { return { ok: true, skipped: true, deliveries: [] } } }
