/* eslint-disable @typescript-eslint/no-explicit-any -- customer relation rows are read server-side from Supabase. */
import type { Metadata } from 'next'
import { UsersRound } from 'lucide-react'

import { AdminEmptyState, AdminPageHeader } from '@/components/admin/admin-shell'
import { getCustomerManagementData } from '@/lib/admin/data'

export const metadata: Metadata = { title: 'Customer operations', robots: { index: false, follow: false } }

export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q } = await searchParams
  const customers = await getCustomerManagementData(q)
  return <div><AdminPageHeader eyebrow="Customer operations" title="Customer records & order history" description="This view is available only to authenticated operational roles. Customers are not destructively deleted because historical orders depend on them." action={<form className="flex w-full gap-2 sm:w-auto" method="get"><input name="q" defaultValue={q ?? ''} placeholder="Name, phone, or email" className="h-10 w-full min-w-56 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-500 sm:w-64" /><button className="h-10 rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white">Search</button></form>} />{customers.length ? <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Contact</th><th className="px-5 py-3">Orders</th><th className="px-5 py-3">Recent order</th><th className="px-5 py-3 text-right">Recent total</th></tr></thead><tbody>{customers.map((customer) => { const orders = [...(customer.orders ?? [])].sort((a: any, b: any) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()); const recent = orders[0]; return <tr key={customer.id} className="border-t border-slate-100"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{customer.full_name}</p><p className="mt-1 text-xs text-slate-500">Customer record since {new Date(customer.created_at).toLocaleDateString('en-BD')}</p></td><td className="px-5 py-4"><p className="text-slate-700">{customer.phone}</p><p className="mt-1 text-xs text-slate-500">{customer.email ?? 'No email stored'}</p></td><td className="px-5 py-4 font-semibold text-slate-900">{orders.length}</td><td className="px-5 py-4">{recent ? <><p className="font-mono text-xs font-semibold">{recent.order_number}</p><p className="mt-1 text-xs text-slate-500">{recent.order_status}</p></> : '—'}</td><td className="px-5 py-4 text-right font-semibold">{recent ? `৳${Number(recent.grand_total).toLocaleString('en-BD')}` : '—'}</td></tr> })}</tbody></table></div></section> : <AdminEmptyState icon={UsersRound} title="No customer records found" description="Customer records are created from legitimate orders. Try another search term or wait for the first order." />}</div>
}
