'use server'

import { z } from 'zod'
import { revalidatePath, updateTag } from 'next/cache'
import { requireAdmin } from './auth'
import { writeAdminAuditLog } from './audit'
import { createAdminClient } from '@/lib/supabase/admin'
import { DEFAULT_ANALYTICS_CONFIG, type AnalyticsConfig } from '@/lib/analytics/server'
import { recordCanonicalEvent } from '@/lib/analytics/events'
import { ANALYTICS_EVENT_REGISTRY } from '@/lib/analytics/registry'
import { isValidServerGtmEndpoint, normalizeServerGtmEndpoint } from '@/lib/analytics/server-gtm'

const configSchema = z.object({ enabled: z.boolean(), marketingEnabled: z.boolean(), consentMode: z.enum(['basic', 'advanced']), debugMode: z.boolean(), ga4MeasurementId: z.string().trim().max(100).refine((value) => !value || /^G-[A-Z0-9]+$/i.test(value), 'Invalid GA4 Measurement ID.'), gtmContainerId: z.string().trim().max(100).refine((value) => !value || /^GTM-[A-Z0-9]+$/i.test(value), 'Invalid GTM Container ID.'), metaPixelId: z.string().trim().max(100), tiktokPixelId: z.string().trim().max(128), tiktokEventsApiEnabled: z.boolean(), metaCapiEnabled: z.boolean(), serverGtmEnabled: z.boolean(), serverGtmEndpoint: z.string().trim().max(2048).refine(isValidServerGtmEndpoint, 'Use a canonical HTTPS server container URL.'), environment: z.enum(['development', 'preview', 'production']), eventControls: z.record(z.string(), z.boolean()).default({}) }).strict()

export async function getAnalyticsAdminConfig() { try { await requireAdmin(['OWNER', 'ADMIN']); const db = createAdminClient(); const { data } = await db.from('settings').select('value').eq('key', 'analytics_config').maybeSingle(); const stored = (data?.value as Partial<AnalyticsConfig> | null) || {}; return { ...DEFAULT_ANALYTICS_CONFIG, ...stored, eventControls: { ...DEFAULT_ANALYTICS_CONFIG.eventControls, ...(stored.eventControls || {}) } } } catch { return DEFAULT_ANALYTICS_CONFIG } }
export async function saveAnalyticsConfig(input: unknown) { try { const session = await requireAdmin(['OWNER', 'ADMIN']); const parsed = configSchema.parse(input); const normalized = { ...parsed, serverGtmEndpoint: normalizeServerGtmEndpoint(parsed.serverGtmEndpoint) }; const db = createAdminClient(); const { error } = await db.from('settings').upsert({ key: 'analytics_config', value: normalized, description: 'Provider-neutral analytics configuration. Credentials remain server environment secrets.', updated_at: new Date().toISOString() }, { onConflict: 'key' }); if (error) throw error; updateTag('analytics-config'); await writeAdminAuditLog({ actorUserId: session.userId, action: 'ANALYTICS_CONFIG_UPDATED', entityType: 'analytics_config', details: { enabled: normalized.enabled, marketingEnabled: normalized.marketingEnabled, consentMode: normalized.consentMode, debugMode: normalized.debugMode, ga4Configured: Boolean(normalized.ga4MeasurementId), gtmConfigured: Boolean(normalized.gtmContainerId), metaPixelConfigured: Boolean(normalized.metaPixelId), tiktokPixelConfigured: Boolean(normalized.tiktokPixelId), tiktokEventsApiEnabled: normalized.tiktokEventsApiEnabled, metaCapiEnabled: normalized.metaCapiEnabled, serverGtmEnabled: normalized.serverGtmEnabled, serverGtmConfigured: Boolean(normalized.serverGtmEndpoint), eventControlCount: Object.keys(normalized.eventControls).length, environment: normalized.environment } }); revalidatePath('/admin/analytics'); return { ok: true, message: 'Analytics configuration saved.' } } catch { return { ok: false, message: 'Unable to save analytics configuration.' } } }
export async function testAnalyticsEvent(eventName: 'page_view' | 'view_item' | 'add_to_cart' | 'begin_checkout' | 'purchase') { try { const session = await requireAdmin(['OWNER', 'ADMIN']); const event = { eventId: crypto.randomUUID(), eventName, eventVersion: '1.0' as const, occurredAt: new Date().toISOString(), sessionId: 'admin-test', anonymousId: null, pageUrl: null, pagePath: null, referrer: null, source: 'admin-test', medium: null, campaign: null, device: null, consent: { necessary: true as const, analytics: true, marketing: true }, commerce: eventName === 'purchase' ? { transaction_id: `TEST-${Date.now()}`, value: 0, currency: 'BDT', items: [] } : {}, testMode: true as const }; const result = await recordCanonicalEvent({ ...event, testMode: true }); await writeAdminAuditLog({ actorUserId: session.userId, action: 'ANALYTICS_TEST_EVENT', entityType: 'analytics_config', details: { eventName, testMode: true, accepted: result.ok, destinations: [] } }); return result.ok ? { ok: true, message: `${eventName} synthetic test recorded safely. No live provider event was sent.` } : { ok: false, message: 'Unable to record analytics synthetic test.' } } catch { return { ok: false, message: 'Unable to run analytics synthetic test.' } } }

export async function getAnalyticsEventOptions() { await requireAdmin(['OWNER', 'ADMIN']); return ANALYTICS_EVENT_REGISTRY.map(({ name, category, marketing, required, description }) => ({ name, category, marketing, required, description })) }
