'use server'

import { z } from 'zod'
import { revalidatePath } from 'next/cache'
import { requireAdmin } from './auth'
import { writeAdminAuditLog } from './audit'
import { createAdminClient } from '@/lib/supabase/admin'
import { DEFAULT_ANALYTICS_CONFIG, type AnalyticsConfig, trackServerCommerceEvent } from '@/lib/analytics/server'
import { ANALYTICS_EVENT_REGISTRY } from '@/lib/analytics/registry'

const configSchema = z.object({ enabled: z.boolean(), marketingEnabled: z.boolean(), consentMode: z.enum(['basic', 'advanced']), debugMode: z.boolean(), ga4MeasurementId: z.string().trim().max(100), gtmContainerId: z.string().trim().max(100), metaPixelId: z.string().trim().max(100), metaCapiEnabled: z.boolean(), serverGtmEndpoint: z.union([z.literal(''), z.string().url().refine((value) => value.startsWith('https://'), 'HTTPS required')]), environment: z.enum(['development', 'preview', 'production']), eventControls: z.record(z.string(), z.boolean()).default({}) }).strict()

export async function getAnalyticsAdminConfig() { try { await requireAdmin(['OWNER', 'ADMIN']); const db = createAdminClient(); const { data } = await db.from('settings').select('value').eq('key', 'analytics_config').maybeSingle(); const stored = (data?.value as Partial<AnalyticsConfig> | null) || {}; return { ...DEFAULT_ANALYTICS_CONFIG, ...stored, eventControls: { ...DEFAULT_ANALYTICS_CONFIG.eventControls, ...(stored.eventControls || {}) } } } catch { return DEFAULT_ANALYTICS_CONFIG } }
export async function saveAnalyticsConfig(input: unknown) { try { const session = await requireAdmin(['OWNER', 'ADMIN']); const parsed = configSchema.parse(input); const db = createAdminClient(); const { error } = await db.from('settings').upsert({ key: 'analytics_config', value: parsed, description: 'Provider-neutral analytics configuration. Credentials remain server environment secrets.', updated_at: new Date().toISOString() }, { onConflict: 'key' }); if (error) throw error; await writeAdminAuditLog({ actorUserId: session.userId, action: 'ANALYTICS_CONFIG_UPDATED', entityType: 'analytics_config', details: { enabled: parsed.enabled, marketingEnabled: parsed.marketingEnabled, consentMode: parsed.consentMode, debugMode: parsed.debugMode, ga4Configured: Boolean(parsed.ga4MeasurementId), gtmConfigured: Boolean(parsed.gtmContainerId), metaPixelConfigured: Boolean(parsed.metaPixelId), metaCapiEnabled: parsed.metaCapiEnabled, serverGtmConfigured: Boolean(parsed.serverGtmEndpoint), eventControlCount: Object.keys(parsed.eventControls).length, environment: parsed.environment } }); revalidatePath('/admin/analytics'); return { ok: true, message: 'Analytics configuration saved.' } } catch { return { ok: false, message: 'Unable to save analytics configuration.' } } }
export async function testAnalyticsEvent(eventName: 'page_view' | 'view_item' | 'add_to_cart' | 'begin_checkout' | 'purchase') { try { const session = await requireAdmin(['OWNER', 'ADMIN']); const result = await trackServerCommerceEvent({ eventId: crypto.randomUUID(), eventName, eventVersion: '1.0', occurredAt: new Date().toISOString(), sessionId: 'admin-test', anonymousId: null, pageUrl: null, pagePath: null, referrer: null, source: null, medium: null, campaign: null, device: null, consent: { necessary: true, analytics: true, marketing: true }, commerce: eventName === 'purchase' ? { transaction_id: `TEST-${Date.now()}`, value: 0, currency: 'BDT', items: [] } : {}, testMode: true }); await writeAdminAuditLog({ actorUserId: session.userId, action: 'ANALYTICS_TEST_EVENT', entityType: 'analytics_config', details: { eventName, testMode: true, accepted: result.ok, destinations: 'deliveries' in result && result.deliveries ? result.deliveries.map((delivery) => delivery.destination) : [] } }); return { ok: true, message: `${eventName} synthetic test completed.` } } catch { return { ok: false, message: 'Unable to run analytics synthetic test.' } } }

export async function getAnalyticsEventOptions() { await requireAdmin(['OWNER', 'ADMIN']); return ANALYTICS_EVENT_REGISTRY.map(({ name, category, marketing, required, description }) => ({ name, category, marketing, required, description })) }
