'use client'

import { useState } from 'react'
import type { AnalyticsConfig } from '@/lib/analytics/server'
import { saveAnalyticsConfig, testAnalyticsEvent } from '@/lib/admin/analytics-actions'

type Diagnostics = { providers: Record<string, string>; events: Array<{ event_id: string; event_name: string; created_at: string; test_mode: boolean; source: string }>; registry: Array<{ name: string; category: string; marketing: boolean; required: boolean; description: string; providers: string[] }> }

export function AnalyticsControlCenter({ initial, diagnostics }: { initial: AnalyticsConfig; diagnostics: Diagnostics }) {
  const [config, setConfig] = useState(initial)
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const [browserHealth, setBrowserHealth] = useState<{ status: string; dataLayer: number; script: boolean; containerId: string } | null>(null)
  const update = <K extends keyof AnalyticsConfig>(key: K, value: AnalyticsConfig[K]) => setConfig((current) => ({ ...current, [key]: value }))
  const updateEvent = (eventName: string, enabled: boolean) => update('eventControls', { ...config.eventControls, [eventName]: enabled })
  async function save() { setBusy(true); const result = await saveAnalyticsConfig(config); setBusy(false); setNotice(result.message) }
  async function test(eventName: 'page_view' | 'view_item' | 'add_to_cart' | 'begin_checkout' | 'purchase') { setBusy(true); const result = await testAnalyticsEvent(eventName); setBusy(false); setNotice(result.message) }
  function verifyBrowserRuntime() { const w = window as typeof window & { dataLayer?: unknown[]; __PHONERBAZAR_GTM__?: { id?: string; status?: string } }; setBrowserHealth({ status: w.__PHONERBAZAR_GTM__?.status || 'NOT_DETECTED', dataLayer: w.dataLayer?.length || 0, script: Boolean(document.getElementById('phonerbazar-gtm')), containerId: w.__PHONERBAZAR_GTM__?.id || '' }) }
  return <div className="space-y-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-600">Commerce observability</p><h2 className="mt-2 text-2xl font-black text-slate-950">Analytics Control Center</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">One canonical event layer feeds optional destinations. Commerce remains functional when every analytics destination is disabled or unavailable.</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${config.enabled ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{config.enabled ? 'Enabled' : 'Disabled'}</span></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">GA4 Measurement ID<input value={config.ga4MeasurementId} onChange={(e) => update('ga4MeasurementId', e.target.value)} placeholder="G-XXXX" className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-semibold text-slate-700">GTM Container ID<input value={config.gtmContainerId} onChange={(e) => update('gtmContainerId', e.target.value)} placeholder="GTM-XXXX" className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Meta Pixel ID<input value={config.metaPixelId} onChange={(e) => update('metaPixelId', e.target.value)} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Server-side GTM endpoint<input type="url" value={config.serverGtmEndpoint} onChange={(e) => update('serverGtmEndpoint', e.target.value)} placeholder="https://..." className="mt-1 w-full rounded-xl border p-3 font-normal" /></label></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={config.enabled} onChange={(e) => update('enabled', e.target.checked)} />Analytics enabled</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={config.marketingEnabled} onChange={(e) => update('marketingEnabled', e.target.checked)} />Marketing tracking enabled</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={config.metaCapiEnabled} onChange={(e) => update('metaCapiEnabled', e.target.checked)} />Meta CAPI enabled</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={config.debugMode} onChange={(e) => update('debugMode', e.target.checked)} />Debug mode</label></div>
      <div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-black text-slate-900">Consent enforcement</p><p className="mt-1 text-xs text-slate-500">Necessary commerce remains active. Analytics and marketing are separate optional categories.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Enforced</span></div></div>
      <div className="mt-5 rounded-xl border border-slate-100 p-4"><p className="text-sm font-black text-slate-900">Event controls</p><p className="mt-1 text-xs text-slate-500">Disable supported events centrally without changing storefront code.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{diagnostics.registry.map((event) => <label key={event.name} className="flex items-start gap-2 rounded-lg border border-slate-100 p-2 text-xs"><input type="checkbox" disabled={event.required} checked={event.required || config.eventControls[event.name] !== false} onChange={(e) => updateEvent(event.name, e.target.checked)} className="mt-0.5" /><span className="min-w-0"><span className="font-bold text-slate-800">{event.name}</span><span className="ml-1 text-[10px] text-slate-400">{event.category}{event.required ? ' · required' : ''}</span><span className="mt-0.5 block text-[10px] leading-4 text-slate-500">{event.description}</span></span></label>)}</div></div>
      <div className="mt-5 flex flex-wrap gap-3"><button type="button" disabled={busy} onClick={save} className="rounded-full bg-slate-950 px-5 py-3 text-sm font-bold text-white">{busy ? 'Saving…' : 'Save configuration'}</button>{notice ? <p role="status" className="self-center text-sm font-semibold text-emerald-700">{notice}</p> : null}</div>
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="text-lg font-black">Provider health and safe test mode</h3><p className="mt-1 text-sm text-slate-500">Health distinguishes configuration from external reachability. GTM reachability verifies that the configured public container endpoint responds; browser execution is separately exposed by the runtime bootstrap.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(diagnostics.providers).map(([label, status]) => <div key={label} className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">{label}</p><p className={`mt-2 text-sm font-black ${status === 'CONFIGURED' || status === 'REACHABLE' ? 'text-emerald-700' : status === 'PARTIAL' ? 'text-amber-700' : status === 'UNREACHABLE' ? 'text-rose-700' : 'text-slate-400'}`}>{status === 'REACHABLE' ? 'Reachable' : status}</p></div>)}</div><div className="mt-5 flex flex-wrap items-center gap-2"><button type="button" onClick={verifyBrowserRuntime} className="rounded-full bg-slate-950 px-3 py-2 text-xs font-bold text-white">Verify browser runtime</button>{browserHealth ? <span className="rounded-full bg-slate-50 px-3 py-2 text-xs font-bold text-slate-700">GTM: {browserHealth.status} · script {browserHealth.script ? 'yes' : 'no'} · dataLayer {browserHealth.dataLayer}{browserHealth.containerId ? ` · ${browserHealth.containerId}` : ''}</span> : null}</div><div className="mt-3 flex flex-wrap gap-2">{(['page_view', 'view_item', 'add_to_cart', 'begin_checkout', 'purchase'] as const).map((eventName) => <button key={eventName} type="button" disabled={busy} onClick={() => test(eventName)} className="rounded-full border border-slate-300 px-3 py-2 text-xs font-bold">Test {eventName}</button>)}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-black">Event diagnostics</h3><p className="mt-1 text-sm text-slate-500">Safe status only. Credentials, authorization headers, and private customer data are never returned.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{diagnostics.events.length} recent events</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(diagnostics.providers).map(([name, status]) => <div key={name} className="rounded-xl border border-slate-100 p-4"><p className="text-xs font-bold text-slate-500">{name}</p><p className={`mt-2 text-sm font-black ${status === 'CONFIGURED' || status === 'REACHABLE' ? 'text-emerald-700' : status === 'PARTIAL' ? 'text-amber-700' : status === 'UNREACHABLE' ? 'text-rose-700' : 'text-slate-400'}`}>{status === 'REACHABLE' ? 'Reachable' : status}</p></div>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b text-slate-500"><th className="p-2">Event</th><th className="p-2">Event ID</th><th className="p-2">Source</th><th className="p-2">State</th><th className="p-2">Time</th></tr></thead><tbody>{diagnostics.events.map((event) => <tr key={event.event_id} className="border-b border-slate-50"><td className="p-2 font-bold">{event.event_name}</td><td className="max-w-48 truncate p-2 font-mono">{event.event_id}</td><td className="p-2">{event.source}</td><td className="p-2">{event.test_mode ? 'TEST' : 'LIVE'}</td><td className="whitespace-nowrap p-2">{new Date(event.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>
  </div>
}
